= Server Platform Task Group Charter

== Introduction

The Server Platform Task Group shall define a specification for a
standardized set of hardware and software capabilities, that portable
system software (such as operating systems and hypervisors) can rely
on being present in a RISC-V server platform.

== Definitions

A server is a computing system that is designed to manage and distribute
resources, services and data to other computers or devices on a network.
It is often referred to as a "server" because it serves or provides
information or resources upon request. Such computing systems are
designed to operate continually and have a higher degree of
requirements on RAS, security, performance, quality of service,
etc. Examples of servers include web servers, file servers, database
servers, mail servers, game servers, etc. The focus of this
specification is to define requirements for general purpose server
computing systems that may be used for one or more of these purposes.

== Background

It is important to standardize the requirements for ISA, hardware
interfaces and capabilities (e.g.  harts, timers, interrupt controllers,
PCIe RCs, RAS, QoS, PMU, etc), software (OS loader interfaces, hardware
description mechanisms) and security (e.g. trusted boot) provided by a
server platform, so that operating system and hypervisor vendors may
support such platforms with a single binary OS image distribution.

Server platform has been chosen as the first platform to standardize,
this being consistent with efforts inside the RISC-V community to
enable general purpose computing platforms. Other platform
standardizaation efforts may follow both within RVI and externally.
Server platform as the first standardized platform is similar to RVA
ISA Profile being standardized as the first RVI profile. In both of
these cases the efforts are driven by markets that most value and
need standardization.

== Objectives

The produced specification will tie together the many hardware and
software requirements for a server platform, many of which are defined
in detail by other RISC-V specs, such as:

* ISA Profiles.
* Boot and Runtime Services.
* Server SoC.
* Platform security Model.

The intent is that most of the normative content is developed by
other TGs and that the server platform specification is the document
that binds everything together and provides a practical architectural
guide to achieve the stated goals.

The specification is meant to be driven by functionality and interoperability
requirements from operating system vendors and solution providers, and thus
concerns itself with systems and application software-observable behavior.
The focus is thus how the system will behave rather than how it will be built.
This is consistent with other specs such as the Server SoC and BRS specifications.

Where applicable, the produced specification shall reference relevant
industry standards.

It is expected that the server platform specification will add
additional (refining) requirements in relevant areas. For example,
the firmware requirements may be more stringent than the ones covered
in the BRS and include server-specific elements. The specification will
be styled in a manner consistent with the related specs (Server SoC).

The server platform TG shall define a coverage plan and approach to
determine compliance to the requirements defined by the
specification. This coverage plan will include and build on the
coverage plans defined by relevant TGs for the dependent specs
(e.g. BRS, Server SoC, etc). This includes a test specification and
a high-level plan for a certification suite (overall design, hosting,
funding, relation to test suites for dependent RVI specifications).

The server platform specification is expected to be updated
periodically to stay up to date with the evolution of dependent
RISC-V and industry specification, and to meet the evolving market
requirements identified by RISC-V International stakeholders.

== Exclusions (Optional)

The specification is not going to cover mechanical, electrical,
thermal, form-factor and performance aspects of a server platform.

== Collaborations

To fulfill its objectives, the Server Platform Task Group will engage with:

* Profiles Working Groups.
* Server SoC Task Group.
* Boot and Runtime Services Task Group.
* Platform Security Model Task Group.

The TG shall be governed by the TSC directly.
